### ISSUE TITLE
Looks like you found an `auto` bug! 

### ISSUE THREAD

**Issue by hipstersmoothie** [jpaulobneto/lerna-auto-publish#4]
I'll fix that 😅

**Comment by jpaulobneto** [comment]
Really? Could you explain it?

**Comment by hipstersmoothie** [comment]
I was looking at your log and found https://circleci.com/gh/jpaulobneto/lerna-auto-publish/19?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

> TypeError: Reduce of empty array with no initial value
>    at Array.reduce (<anonymous>)
>    at Git.getTagNotInBaseBranch (/home/circleci/repo/node_modules/@auto-it/core/dist/git.js:601:48)
>    at processTicksAndRejections (internal/process/task_queues.js:97:5)
>    at async Auto.next (/home/circleci/repo/node_modules/@auto-it/core/dist/auto.js:776:25)

I've opened a PR fixing the bug https://github.com/intuit/auto/pull/1249

and tested on your repo using --dry-run

<img width="1151" alt="Screen Shot 2020-05-22 at 9 58 39 PM" src="https://user-images.githubusercontent.com/1192452/82721982-681d1880-9c77-11ea-8d2e-ec059af32e27.png">

**Comment by jpaulobneto** [comment]
Thank you! I'll try it now!
